### ISSUE TITLE
Some new content that could be added

### ISSUE THREAD

**Issue by Darthagnon** [scowalt/PlayniteExtensionList#2]
Theme:
Classic Steam
https://playnite.link/forum/thread-299.html
https://gitlab.com/xyifer12/ClassicSteam-Playnite-Theme

Author: [xyifer12](https://gitlab.com/xyifer12)

Old Steam Library theme, how it looked *before* the [All New Steam Library update](https://store.steampowered.com/libraryupdate)

Banners
https://famicomrade.github.io/
(website that sources them from: https://playnite.link/forum/thread-314.html)

(misc authors on Playnite forums) Aggregator: [Famicomrade](https://playnite.link/forum/user-570.html)

Banners to display over game box art.

**Comment by scowalt** [comment]
I added Classic Steam with bf8b48743e5204646e6153131f46d07eb5cfeaf6

I want to keep this list restricted to only Extensions and Themes (things an end-user of Playnite would install). Are these banners intended for theme developers? If so, I'm leaving that out of scope for this list.
